// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(LectureGroupContext))]
    [Migration("20220623135315_InitalMigration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Domain.AcademicStaff", b =>
                {
                    b.Property<Guid>("AcademicStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("AcademicStaffId");

                    b.ToTable("AcademicStaff");
                });

            modelBuilder.Entity("Domain.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Domain.Course_AcademicStaff", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AcademicStaffId")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId", "AcademicStaffId");

                    b.HasIndex("AcademicStaffId");

                    b.ToTable("Course_AcademicStaff");
                });

            modelBuilder.Entity("Domain.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AcademicStaffId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LectureGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LectureHallId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LectureType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("LectureId");

                    b.HasIndex("LectureGroupId");

                    b.HasIndex("LectureHallId");

                    b.HasIndex("CourseId", "AcademicStaffId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.Property<int>("LectureGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LGRSId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("TEXT");

                    b.HasKey("LectureGroupId");

                    b.HasIndex("LGRSId");

                    b.ToTable("LectureGroups");
                });

            modelBuilder.Entity("Domain.LectureGroupRegisteringSeason", b =>
                {
                    b.Property<int>("LGRSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamSeasonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faculty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("LGRSId");

                    b.ToTable("LGRS");
                });

            modelBuilder.Entity("Domain.LectureHall", b =>
                {
                    b.Property<int>("LectureHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HallName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.HasKey("LectureHallId");

                    b.ToTable("LectureHalls");
                });

            modelBuilder.Entity("Domain.Course_AcademicStaff", b =>
                {
                    b.HasOne("Domain.AcademicStaff", "AcademicStaff")
                        .WithMany("CourseAcademicStaff")
                        .HasForeignKey("AcademicStaffId")
                        .HasConstraintName("academicStaffCourse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Course", "Course")
                        .WithMany("CourseAcademicStaff")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("courseAcademicStaff")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicStaff");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Lecture", b =>
                {
                    b.HasOne("Domain.LectureGroup", "LectureGroup")
                        .WithMany("Lectures")
                        .HasForeignKey("LectureGroupId")
                        .HasConstraintName("Lectures_Groups")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.LectureHall", "LectureHall")
                        .WithMany("Lectures")
                        .HasForeignKey("LectureHallId")
                        .HasConstraintName("Lectures_Halls")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Course_AcademicStaff", "Course_AcademicStaff")
                        .WithMany("Lectures")
                        .HasForeignKey("CourseId", "AcademicStaffId")
                        .HasConstraintName("courseAcademicSTAFF_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course_AcademicStaff");

                    b.Navigation("LectureGroup");

                    b.Navigation("LectureHall");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.HasOne("Domain.LectureGroupRegisteringSeason", "LGRS")
                        .WithMany("LectureGroups")
                        .HasForeignKey("LGRSId")
                        .HasConstraintName("LG_LGRS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGRS");
                });

            modelBuilder.Entity("Domain.AcademicStaff", b =>
                {
                    b.Navigation("CourseAcademicStaff");
                });

            modelBuilder.Entity("Domain.Course", b =>
                {
                    b.Navigation("CourseAcademicStaff");
                });

            modelBuilder.Entity("Domain.Course_AcademicStaff", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Domain.LectureGroupRegisteringSeason", b =>
                {
                    b.Navigation("LectureGroups");
                });

            modelBuilder.Entity("Domain.LectureHall", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
