// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(LectureGroupContext))]
    partial class LectureGroupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Domain.Lecture", b =>
                {
                    b.Property<int>("LectureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AcademicStaff")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LectureGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LectureHallId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LectureType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("LectureId");

                    b.HasIndex("LectureGroupId");

                    b.HasIndex("LectureHallId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.Property<int>("LectureGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("LGRSId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("TEXT");

                    b.HasKey("LectureGroupId");

                    b.HasIndex("LGRSId");

                    b.ToTable("LectureGroups");
                });

            modelBuilder.Entity("Domain.LectureGroupRegisteringSeason", b =>
                {
                    b.Property<int>("LGRSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamSeasonStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Faculty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("LGRSId");

                    b.ToTable("LGRS");
                });

            modelBuilder.Entity("Domain.LectureHall", b =>
                {
                    b.Property<int>("LectureHallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HallName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.HasKey("LectureHallId");

                    b.ToTable("LectureHalls");
                });

            modelBuilder.Entity("Domain.Lecture", b =>
                {
                    b.HasOne("Domain.LectureGroup", "LectureGroup")
                        .WithMany("Lectures")
                        .HasForeignKey("LectureGroupId")
                        .HasConstraintName("Lectures_Groups")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.LectureHall", "LectureHall")
                        .WithMany("Lectures")
                        .HasForeignKey("LectureHallId")
                        .HasConstraintName("Lectures_Halls")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LectureGroup");

                    b.Navigation("LectureHall");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.HasOne("Domain.LectureGroupRegisteringSeason", "LGRS")
                        .WithMany("LectureGroups")
                        .HasForeignKey("LGRSId")
                        .HasConstraintName("LG_LGRS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGRS");
                });

            modelBuilder.Entity("Domain.LectureGroup", b =>
                {
                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("Domain.LectureGroupRegisteringSeason", b =>
                {
                    b.Navigation("LectureGroups");
                });

            modelBuilder.Entity("Domain.LectureHall", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
